### ISSUE TITLE
Bitbucket Server - Delete CxSAST project on DELETE event

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#645] opened 2021-02-17 17:49 UTC
### Describe the problem

Bitbucket Server DELETE branch events are not picked up by CxFlow so the project is not deleted in CxSAST like in other SCM providers.
This is required so CxSAST doesn't end up with too many useless, Pull Request generated, projects that need to be manually deleted.

### Proposed solution

When a non-protected branch (like a PR branch) is deleted on Bitbucket Server UI or through a REST call, the CxFlow should interpret the webhook event and then delete the project in CxSAST.

### Additional details

This is similar to the behavior in other SCM provider DELETE events behavior like GitHub and GitLab.
If possible, make this compatible at least from Bitbucket Server 7.6.0 and above.

Bitbucket Cloud appears to send a push event once it closes/deletes a project (I cannot confirm this), so if possible to have the delete event to delete CxSAST projects on both servers by identifying any information in that push event that might help identifying that it's deleting the project would be great.

**Comment by nleach999** [comment] 2021-02-22 13:19
Dupe of issue #644.  We both must have looked at this on the same day. 👍 

It might be a good idea to consider the concept of issue #556 in handling project deletes.  Issue #556 indicates PR closed as the criteria for project deletion.  It might be better to do the project delete on PR merge rather than close.

**Comment by cx-scord** [comment] 2021-02-22 13:26
@nleach999 Yes, I agree, there could be an option to have a branch deleted on either of those, or when the PR is closed/merged or Deleted, the "closed"/"merged" event might also help on Bitbucket cloud (and, for example, have the "delete" event documented as not being supported in Bitbucket cloud).

PS - Sorry for the duplcate, but I started writing this issue and doing some tests after I didn't find anything related to this, we contributed almost the same time :)

**Comment by HussainS12** [comment] 2022-02-17 10:21
This is fixed in PR #932

**Closed by HussainS12** 2022-02-17 10:21 UTC
Labels: enhancement
